### ISSUE TITLE
--semver doesn't accept some ranges

### ISSUE THREAD

**Issue by jdalton** [anvaka/npmrank#10]
I noticed issues specifying ranges as `>=1.0.0` or `<0.15.0`

**Comment by anvaka** [comment]
Traced it down to two separate issues:

https://github.com/izaakschroeder/semver-set/issues/2
https://github.com/izaakschroeder/semver-set/issues/3

**Comment by jdalton** [comment]
Thanks for digging.

**Comment by jdalton** [comment]
@anvaka Is the [node-semver](https://github.com/npm/node-semver) package an option? It's maintained by izs so it's guaranteed good.

**Comment by jdalton** [comment]
I changed the `package.json` entry to
```json
"semver-set": "git://github.com/voxpelli/semver-set.git#7fc070b53130604a9749a642e496ded9aecad98a"
```
and it resolved the issue.

**Comment by anvaka** [comment]
Thank you! I updated the package.json

**Comment by jdalton** [comment]
It's not ideal (if the fork is deleted then it goes down) but it's a good temp solution.
