### ISSUE TITLE
"sounds like" option.

### ISSUE THREAD

**Issue by jdalton** [anvaka/npmrank#13]
This is a bit outside ranking but it would be neat to be able to see which packages have similar names.
For example if I search for "lodash" and there's a "lodasj" package then it would be in the results.

**Comment by anvaka** [comment]
Added `soundsLike.js`. Download the graph using [01_get_graph.sh](https://github.com/anvaka/npmrank/blob/master/01_get_graph.sh), then run 

```
node soundsLike.js [packageName]
```

For lodash:

```
> node soundsLike.js lodash
Reading packages from ./data/byField.in.graph...
bdash
bsdash
codash
dash
docdash
dotdash
emdash
esdash
florash
fodash
godash
hidash
kodash
lash
leash
lo-dash
loda
lodashed
lodashim
lodashsh
logasm
lomash
lomath
longdash
luadash
ludash
mdash
mldash
ndash
nedash
nodash
nodast
nodish
prodash
redash
vudash
```

I'm using [Levenshtein](https://en.wikipedia.org/wiki/Levenshtein_distance) distance for this.

I also tried SoundEx and Metaphone from [natrual](https://www.npmjs.com/package/natural) - didn't like the results. But if someone knows a good suitable phonetic algorithm I'd be happy to add it.

**Comment by jdalton** [comment]
Thank you! This is helpful for finding name squatters.
