### ISSUE TITLE
gist misreading.

### ISSUE THREAD

**Issue by jdalton** [anvaka/npmrank#14]
I noticed the auto-updated gist is getting incorrect results more often:
https://gist.github.com/anvaka/8e8fa57c7ee1350e3491/08a54be7bd3120bf6353c68d64eb23e91b5542ee

Might be something to guard against somewhere.

> - Date: Sat, 30 Jul 2016 07:01:13 GMT
> - Input file: `./data/dependenciesGraph.out.graph`
> # Top 1000 most depended-upon packages
> 1. [lodash](https://www.npmjs.org/package/lodash) - 2884
> 2. [request](https://www.npmjs.org/package/request) - 1849
> 3. [async](https://www.npmjs.org/package/async) - 1842
> 4. [underscore](https://www.npmjs.org/package/underscore) - 1796
> 5. [commander](https://www.npmjs.org/package/commander) - 1199

**Comment by jdalton** [comment]
```md
* Date: Sat, 30 Jul 2016 07:01:13 GMT
* Input file: `./data/dependenciesGraph.out.graph`

# Top 1000 most depended-upon packages

0. [lodash](https://www.npmjs.org/package/lodash) - 2884
1. [request](https://www.npmjs.org/package/request) - 1849
2. [async](https://www.npmjs.org/package/async) - 1842
3. [underscore](https://www.npmjs.org/package/underscore) - 1796
4. [commander](https://www.npmjs.org/package/commander) - 1199
```

**Comment by anvaka** [comment]
Thanks for reporting this! I just wanted to admit that I see the problem. I'll try to find some time this week to address it. Briefly looking at the code I can't spot any obvious error and the host that generated this gist already wiped out the data.

**Comment by anvaka** [comment]
Looks like sometimes registry does not give full response and curl fails. I [added `&&`](https://github.com/anvaka/npmrank/commit/c6f43233ba6a1bc83b42e78e8d72893d73f82cf3) - hopefully that will prevent the program from committing broken response. I still need to figure out how to do retries or receive alerts when no commit was made.
