### ISSUE TITLE
Impact of authors.

### ISSUE THREAD

**Issue by jdalton** [anvaka/npmrank#3]
It would be neat to have a report that finds the impact of package authors. Maybe taking their list of packages and reporting them as if they were matched by the `countTotalDeps.js` regexp.

**Comment by anvaka** [comment]
Interesting! How do you define `impact`? Is this number of packages created by author?

**Comment by jdalton** [comment]
impact as in the direct/indirect + dep count & percentage of npm registry as `countTotalDeps` reports.

**Comment by anvaka** [comment]
So, for example `40,364` unique packages depend on `^lodash(-(amd|compat|node)|\.\w+)?$` out of total `177,194` packages. That would be `22.780%` author impact?

**Comment by jdalton** [comment]
Ya don' get hungup on the `impact` wording. But that's the idea. You could point to say substack and then it would report that 48% of npm packages depend on his work.

**Comment by anvaka** [comment]
Ah, I see now! This should be fixed, though it will require to rerun `convertToGraph.js`.

I have also updated readme file with tinstructions.

**Comment by jdalton** [comment]
I'm getting:
```bash
Found 0 matches
[]
0 unique packages depend on jdalton out of total 178018 packages
That is 0.000%
```

**Comment by jdalton** [comment]
Ah `node ./countAuthorDeps.js thlorenz` works great! Wow!
