### ISSUE TITLE
get version info by semver range

### ISSUE THREAD

**Issue by jdalton** [anvaka/npmrank#8]
Related to #6 it would be nice to be able to specify a semver range and get the count of deps that could receive it. I'm trying to answer the question, "What percentage of my dependents have updated to at least version 3.0".

**Comment by anvaka** [comment]
Seem to be fairly straightforward. Will do later tonight :).

**Comment by anvaka** [comment]
Oops, commit title is wrong (1:00 am now) but this should be fixed now. E.g.:

```
node countVersions.js lodash --semver='3.9.x'
```

This will count only those packages who would get lodash@3.9.x

**Comment by anvaka** [comment]
I'm building an HTTP interface to npmrank. The temporary experimental stealth server can currently answer these queries:

* http://107.170.226.67:3000/graph/dependent/lodash - Print a dot file with all transitive dependents
* http://107.170.226.67:3000/graph/dependent/lodash/stats - Print graph summary for lodash. Summary includes number of edges and nodes in transitive dependents graph.
* http://107.170.226.67:3000/graph/version/lodash - Print *names* of all direct dependents of lodash
grouped by required version of lodash.
* http://107.170.226.67:3000/graph/version/lodash/stats - Print *number* of direct dependents of lodash grouped by required version of lodash

Would love your feedback regarding API. Longer-term hope is to build web interface on top of it.
